### ISSUE TITLE
Feature Request: Display new line for sequence labeling tasks

### ISSUE THREAD

**Issue by GeorgeXiaojie** [chakki-works/doccano#376]
### Describe the problem

I want label one document which has multi-line, and i reorganize it as following,

```
a b c <br> d e f g <br> h i j k
```

but it still display all content in one row, and i want display like this

```
a b c
d e f g
h i j k
```

Could you add this feature for the multi-line scene?

Thank you very much for your sharing.

**Comment by c-w** [comment]
See https://github.com/chakki-works/doccano/pull/34 which discussed this feature.

**Comment by icoxfog417** [comment]
doccano separates each data by line break now. But you can use the hack that replace line break to `\n`. Please refer #330.

**Comment by GeorgeXiaojie** [comment]
If the project type is document classification, replace line break with \n and save as a json file,  it works. But if the project type is sequence labeling, it does not work through reaplace line break as mentioned in #330 .

**Comment by icoxfog417** [comment]
Line breaks are not supported in sequence labeling because this task is sensitive to character position.

**Comment by davidolmo** [comment]
+1 to this request. I just setted up doccano and was amazed by the library. The problem is that if you have a huge document with multiple sequence labeling categories, new lines are mandatory (otherwise the whole document is a mess). It is a pity that I couldn't use it because of this issue

**Comment by DSLituiev** [comment]
+1, this is a very important feature. 

In medical text I work with NER cannot be disambiguated w/o line breaks
Please consider re-opening.

**Comment by c-w** [comment]
@armanrahman22 was working on this; any update on progress?

**Comment by bgraf422** [comment]
+1, I agree with @DSLituiev, this is an essential feature for medical text.  Most documents contain multiple sections separated by line breaks and without them the documents are a mess.

**Comment by DSLituiev** [comment]
Can someone re-open this issue to make it visible? @c-w 

I changed [this line of annotation.css](https://github.com/doccano/doccano/blob/master/app/server/static/assets/css/annotation.css#L164), and it works like a charm. 

```
 .content .text-sequence {
-  white-space: normal; /* Not render newlines for sequence labelling */
-  height: auto;
+  white-space: pre-wrap;
 }
```
![image](https://user-images.githubusercontent.com/8426290/78094282-08964100-7389-11ea-830b-735ebee0b112.png)

I see no undesirable side effects. Why not just fix it?

**Comment by Hironsan** [comment]
Resolved in https://github.com/doccano/doccano/pull/654.

**Comment by DSLituiev** [comment]
@Hironsan for some reason I see a different frontend than one in #654 (old, without subtitle) when I build from master.

**Comment by buriy** [comment]
Please fix "old" frontend too!

**Comment by antisrdy** [comment]
**Describe the problem**

I'm still facing the issue described in this thread despite all hacks that were mentioned.

Using Doccano through Docker (see this [section](https://github.com/doccano/doccano#docker) of the README), Google Chrome or Edge as browsers, and `Text Classification` task

Using a JSONL file:
```
{"text": "This is a test\nThis is a test","labels":[]}
{"text": "This is a test \n This is a test","labels":[]}
```


Here is what I see on the screen:
 
![Capture d’écran 2021-03-25 125647](https://user-images.githubusercontent.com/8373066/112469328-a557a880-8d69-11eb-8cc0-dd6396d7c8cf.png)

The blank line is well rendered in the code of the page, but not on the screen.

Any idea about how to solve this?
